#Configuration for robot odometry EKF

frequency: 50

two_d_mode: true

publish_tf: false

odom_frame: odom
base_link_frame: base_footprint
world_frame: odom
#map_frame: map

odom0: /noisy_odom
odom0_config: [false, false, false, false, false, true, true, true, false, false, false, true, false, false, false]
odom)_differential: false

imu0: /imu/data
imu0_config: [false, false, false, false, false, true, false, false, false, false, false, true, true, false, false]

imu0_differential: false
